[package]
name = "sysx"
version = "0.4.1"
edition = "2024"

[dependencies]
rand = "0.9.0"
thiserror = "2.0.11"
once_cell = "1.20.3"
colored = "3.0.0"
chrono = "0.4.39"

[dependencies.regex]
version = "1.11.1"
default-features = false
features = ["std", "unicode-perl"]

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
