[package]
name = "sysx"
version = "0.6.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
rand = "0.9.0"
chrono = "0.4.39"
anyhow = "1.0.96"
colored = "3.0.0"
thiserror = "2.0.11"
once_cell = "1.20.3"
shell-words = "1.1.0"
lazy_static = "1.5.0"

[dependencies.parking_lot]
version = "0.12.3"
features = ["deadlock_detection", "nightly"]

[dependencies.regex]
version = "1.11.1"
default-features = false
features = ["std", "unicode-perl"]

[dev-dependencies]
tempfile = "3.17.1"
