[package]
name = "sysx"
version = "0.5.2"
edition = "2024"

[dependencies]
rand = "0.9.0"
colored = "3.0.0"
chrono = "0.4.39"
anyhow = "1.0.96"
thiserror = "2.0.11"
once_cell = "1.20.3"
shell-words = "1.1.0"
lazy_static = "1.5.0"

[dependencies.parking_lot]
version = "0.12.3"
features = ["deadlock_detection", "nightly"]

[dependencies.regex]
version = "1.11.1"
default-features = false
features = ["std", "unicode-perl"]

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
